[package]
name = "utf16_reader"
version = "0.1.0"
authors = ["Bubblepoint <t.matt81@gmail.com>"]
edition = "2018"
description = "Reader for UTF16 files for Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
